id: AFFB8E885
title: A Prayer to Mañjuśrī
type: translation
pechas:
- IFD69663B
- I4FD77B48
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:29:43.901050
  last_modified_at: 2023-01-04 11:29:43.901062
  collections:
  - Apang Tertön Series
  - Works of Tibetan Masters
alignment_to_base:
  IFD69663B/025C: 21FD
  I4FD77B48/77E2: 21FD
